name: Publish Docker Image

on:
  push:
    branches:
    - 'releases/**'

jobs:
  publish-docker-image:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Publish Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tschaffter/${{ github.event.repository.name }}
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/heads/') }}